fix docker build

diff --git a/Dockerfile.goreleaser b/Dockerfile.goreleaser
--- a/Dockerfile.goreleaser
+++ b/Dockerfile.goreleaser
@@ -22,9 +22,12 @@ RUN apt-get -y update && apt-get install -qq -y --no-install-recommends \
     libde265-dev \
     libx265-dev \
     libjpeg62-turbo-dev \
+    libwebm-dev \
+    aom-tools \
     # libavif
     libaom-dev \
-    libyuv-dev
+    libyuv-dev \
+    && apt-get clean && rm -fr /var/lib/apt/lists/*
 
 # Build libjxl
 #RUN git clone -b v${LIBJXL_VERSION} https://github.com/libjxl/libjxl.git --depth 1 --recursive --shallow-submodules && \
@@ -32,39 +35,44 @@ RUN apt-get -y update && apt-get install -qq -y --no-install-recommends \
 #    cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=OFF -DJPEGXL_FORCE_SYSTEM_BROTLI=ON -DJPEGXL_FORCE_SYSTEM_LCMS2=ON -DJPEGXL_ENABLE_TOOLS=OFF -DJPEGXL_ENABLE_EXAMPLES=OFF .. && \
 #    cmake --build . -- -j$(nproc) && \
 #    cmake --install . && \
-#    ldconfig /usr/local/lib
+#    ldconfig /usr/local/lib && \
+#    cd / && rm -fr libjxl
 
 # Build libavif (TODO: don't build from sources as soon as a new release includes the orientation fix: https://github.com/AOMediaCodec/libavif/issues/2727)
-RUN git clone -b v${LIBAVIF_VERSION} https://github.com/AOMediaCodec/libavif.git && \
+RUN git clone -b v${LIBAVIF_VERSION} --depth 1 https://github.com/AOMediaCodec/libavif.git && \
     cmake -S libavif -B libavif/build -DAVIF_CODEC_AOM=SYSTEM -DAVIF_BUILD_APPS=ON && \
     cmake --build libavif/build --config Release --parallel && \
     cmake --install libavif/build && \
-    ldconfig /usr/local/lib
+    ldconfig /usr/local/lib && \
+    cd / && rm -fr libavif
 
 # Build libheif
 RUN git clone -b v${LIBHEIF_VERSION} --depth 1 https://github.com/strukturag/libheif.git && \
     cd libheif/ && mkdir build && cd build && \
     cmake --preset=release .. && \
-    make && make install && \
-    ldconfig /usr/local/lib
+    make -j"$(nproc)" && make install && \
+    ldconfig /usr/local/lib && \
+    cd / && rm -fr libheif
 
 # Build ImageMagick with AVIF & JXL read/write support
 RUN git clone -b ${IMAGE_MAGICK_VERSION} --depth 1 https://github.com/ImageMagick/ImageMagick.git && \
     cd ImageMagick && \
     LIBS="-lsharpyuv" ./configure --without-magick-plus-plus --disable-docs --disable-static --with-tiff --with-jxl --with-heic --with-tcmalloc && \
-    make && make install && \
-    ldconfig /usr/local/lib
+    make -j"$(nproc)" && make install && \
+    ldconfig /usr/local/lib && \
+    cd / && rm -fr ImageMagick
 
 # Download prebuilt Caesium bin
 ARG TARGETPLATFORM
-RUN CAESIUM_LATEST_RELEASE=$(curl -s https://api.github.com/repos/Lymphatus/caesium-clt/releases/latest | jq -r '.tag_name') && \
+RUN CAESIUM_VER=$(curl -sf https://api.github.com/repos/Lymphatus/caesium-clt/releases/latest | jq -r '.tag_name') || { echo "Failed to fetch Caesium latest release"; exit 1; } && \
     if [ "$TARGETPLATFORM" = "linux/amd64" ]; then CAESIUM_ARCH=x86_64-unknown-linux-musl; \
     elif [ "$TARGETPLATFORM" = "linux/arm64" ]; then CAESIUM_ARCH=aarch64-unknown-linux-musl; \
-    else echo "Platform not supported by Lymphatus/caesium-clt"; exit 126; fi && \
-    CAESIUM_ARCHIVE=caesiumclt-${CAESIUM_LATEST_RELEASE}-${CAESIUM_ARCH} && \
-    curl -sS -L -O --output-dir /tmp/ --create-dirs  "https://github.com/Lymphatus/caesium-clt/releases/latest/download/${CAESIUM_ARCHIVE}.tar.gz" && \
-    tar xzf "/tmp/${CAESIUM_ARCHIVE}.tar.gz" -C /tmp && \
-    mv "/tmp/${CAESIUM_ARCHIVE}/caesiumclt" /usr/local/bin/caesiumclt
+    else echo "Platform not supported by Lymphatus/caesium-clt"; exit 1; fi && \
+    CAESIUM_ARCHIVE=caesiumclt-${CAESIUM_VER}-${CAESIUM_ARCH} && \
+    curl -sfSL -o /tmp/caesium.tar.gz "https://github.com/Lymphatus/caesium-clt/releases/download/${CAESIUM_VER}/${CAESIUM_ARCHIVE}.tar.gz" && \
+    tar xzf /tmp/caesium.tar.gz --strip-components 1 -C /tmp && \
+    mv "/tmp/caesiumclt" /usr/local/bin/caesiumclt && \
+    rm -fr /tmp/*
 
 FROM debian:sid-slim
 ENV DEBIAN_FRONTEND=noninteractive
@@ -89,7 +97,7 @@ RUN apt-get -y update && apt-get install -qq -y --no-install-recommends \
     # libavif deps
     libaom3 \
     libyuv0 \
-    && apt-get clean && rm -rf /var/lib/apt/lists/*
+    && apt-get clean && rm -fr /var/lib/apt/lists/*
 
 # Copy libavif, libheif, ImageMagick, caesiumclt from builder
 COPY --from=builder /usr/local /usr/local
